[package]
name = "bitcoin_rpc_errors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro-magic = { path = "proc-macro-magic" }
regex = "1.8.4"